# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4b36b86e5d4d417aa4a3c74b6cd90dc4c00a4e02fb77d535465c06411cee5b5fdd4322d7d36903da1453c5a895f0599fa9f4890ac635d858339cfa0a7b9ac6dc

test:
  secret_key_base: f6d5cde8cf2647f291afd6ab8b8b0cadb59643344bc547cba657da7718a0912bb3d8b8e042bb0b0d544c0045128e45dd88433d52d6f7596d6e82857faf3e54ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
